trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo 'Iniciando la construcción y pruebas unitarias...'
  displayName: 'Iniciando construcción'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Instalar dependencias Python'

- script: |
    python -m unittest tests/test_main.py
  displayName: 'Ejecutar pruebas unitarias'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/temperatura-app.zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'temperatura-app'
