apiVersion: v1
kind: Service
metadata:
  name: temperatura-app-service
  namespace: tech.prod
spec:
  type: ClusterIP
  selector:
    app: temperatura-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000